sneaky/groupapp/urls.py
from django.urls import path, re_path
from .views import chat, room,rooms
from django.conf.urls import url

app_name = 'groupapp'

urlpatterns = [
    path('', chat, name='chat'),
    url(r'^group',rooms,name='rooms'),
    re_path(r'^(?P<room_name>[^/]+)/$', room, name='room'),
]

sneaky/sneaky/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'posts/',include('posts.urls')),
    url(r'index/',include('Userauthapp.urls')),
    url(r'chat/',include('groupapp.urls'))

]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sneaky/templates/base.html
<!doctype html>
<html lang="en">
  <head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.0.min.js"></script>



    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>
<!--       .navbar {-->
<!--  min-height: 80px;-->
<!--}-->

<!--.navbar-brand {-->
<!--  padding: 0 15px;-->
<!--  height: 80px;-->
<!--  line-height: 80px;-->
<!--}-->
<!--&lt;!&ndash;.nav a{&ndash;&gt;-->
<!--&lt;!&ndash;    color: !important;&ndash;&gt;-->
<!--&lt;!&ndash;    font-size: 1.8em !important;&ndash;&gt;-->
<!--&lt;!&ndash;    }&ndash;&gt;-->

<!--.navbar-toggle {-->
<!--  /* (80px - button height 34px) / 2 = 23px */-->
<!--  margin-top: 23px;-->
<!--  padding: 9px 10px !important;-->
<!--}-->

<!--@media (min-width: 768px) {-->
<!--  .navbar-nav > li > a {-->
<!--    /* (80px - line-height of 27px) / 2 = 26.5px */-->
<!--    padding-top: 26.5px;-->
<!--    padding-bottom: 26.5px;-->
<!--    line-height: 27px;-->
<!--  }-->
<!--}-->
    </style>
  </head>
  <body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#"  style="color: !important;font-size: 1.8em !important;"><h1 class="text-primary">Chat room</h1></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    </ul>
      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'posts' %}"  style="color: !important;font-size: 1.2em !important;">Post</a>
      <a class="nav-link" href="{% url 'post-create' %}"  style="color: !important;font-size: 1.2em !important;">New Post</a>
       <a class="nav-link" href="{% url 'groupapp:rooms' %}"  style="color: !important;font-size: 1.2em !important;">Groups</a>
      <a class="nav-link" href="{% url 'logout_user' %}"  style="color: !important;font-size: 1.2em !important;">Logout <span class="sr-only">(current)</span></a>
      <a class="nav-link" href="{% url 'profile' %}"  style="color: !important;font-size: 1.2em !important;">Profile <span class="sr-only">(current)</span></a>
<!--      </li>-->
      {% else %}
<!--    <li class="nav-item ">-->
        <a class="nav-link" href="{% url 'login_user' %}"  style="color: !important;font-size: 1.2em !important;">Login</a>
<!--      </li>-->

        <a class="nav-link" href="{% url 'register_user' %}"  style="color: !important;font-size: 1.2em !important;">Sign UP</a>

    </ul>
      {% endif %}


  </div>
</nav>
   <br>
    <br>
    <br>
    <div>
{% if messages %}
    {% for i in messages %}
    <div class="alert alert-primary" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
      {{ i }}
    </div>
    {% endfor %}
    {% endif %}
{% block content %}
{% endblock %}
    <br>
     <br>
     <br>
     <br>
        </div>

</body>
</html>

sneaky/templates/chat.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br>
 {% if user.is_authenticated %}

<h3>What chat room would you like to enter?</h3><br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

{% else %}
<h3 class="text-center">OOPS! you need to login to use our chat rooms.</h3><br>
{% endif %}

    <!-- chat/templates/chat/index.html -->


    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>

{% endblock %}

sneaky/templates/chatroom.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
.sent {
  float: right;

}
.sent span{
margin-right: 5px;
margin-left: 20px;}
.left {
  float: right;
  margin-right: 20px;
margin-left: 5px;
#scroll * {
  overflow-anchor: none;
}
}

</style>
<br>
 {% if user.is_authenticated %}
<script src=
"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
<div class="card sticky-top">
<h2 class="text-center"> <span class="badge badge-secondary">welcome to chatroom {{ room_name }}</span></h2>
<h4 class="text-center"> {{ username }}</h4>
</div>
<div class="jumbotron jumbotron-fluid" id="scroll">
  <div class="container">
	  <ul class="list-group" id="chat-log">

	  </ul>
      <br>
	  <br>
    <input type="text" class="form-control" id="chat-message-input">
      <br>
	  <button id="chat-message-submit" class="btn btn-primary" type="button" value="Send" onclick = "gfg_Run()">Send</button>

</div>
</div>
{% else %}
<h3 class="text-center">OOPS! you need to login to use our chat rooms.</h3><br>
{% endif %}
<script>
$(document).ready(function() {
            $("button").click(function() {
                $(document).scrollTop($(document).height());
            });
        });
    </script>
{{ room_name|json_script:"room-name" }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
<script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        var endpoint='';
        var username = {{ username }};

        console.log(window.location);
        var wsstart='ws://'+window.location.host+'/ws'+window.location.pathname;
        console.log(wsstart);
        const chatSocket = new ReconnectingWebSocket(wsstart);


        chatSocket.onopen=function(e){
        console.log("web scoket is opened from the front end");

        };
        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            console.log(data);
            var author = data['author'];
            var li=document.createElement('li');


            var division=document.createElement('div');
            var msg=document.createElement('h5');
              msg.textContent=data.message;



       var auth = document.createElement('span');
       auth.textContent = author ;

      if (author === username) {
        division.className = 'sent';
      } else {
        division.className = 'replies';
      }

              msg.appendChild(auth);

              division.appendChild(msg);
              li.appendChild(division);
			  document.querySelector('#chat-log').appendChild(li);
			  $('li').last().addClass("list-group-item");
			  $('span').last().addClass("badge badge-pill badge-primary");
            console.log("message came from websocket");
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };


        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            console.log("i am working upto here send");
            chatSocket.send(JSON.stringify({
                'message': message,
                'from': username
            }));
            messageInputDom.value = '';
        };

    </script>
{% endblock %}

sneaky/templates/group.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h1 class="text-center">Group chat</h1>
<p class="text-center"> Page under construction</p>
{% endblock %}

sneaky/templates/index.html
{% load static %}

<html lang="en">
  <head>


    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script type="text/javascript" src="//code.jquery.com/jquery-2.1.0.min.js"></script>
    <link rel="stylesheet" href="leaflet.css">
    <script src="jquery-2.1.0.min.js"></script>
    <script src="leaflet.js"></script>
    <script src="osmfield.js"></script>
    <!-- Bootstrap CSS -->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link rel=”stylesheet” href=”https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style>

    </style>
  </head>
  <body>


  <div class="container login-container">
      <div class="shadow-sm p-3 mb-5 bg-white rounded">
          <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="d-block w-100" src="..." alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="..." alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="..." alt="Third slide">
            </div>
          </div>
        </div>
      <div class="row">
        <div class="col-md-4 ads">
            <div class="profile-img">
                        <img class="img-fluid"  src="{% static 'images/bck.jpg' %}" height="550" width="350">
                        </div>
            </div>
            <div class="col-md-6 login-form">
                <div class="text-center">
                    <div class="profile-img">

                        </div>
                </div>


                        <h1 class="text-center">LOG-IN</h1>


            <form>
                {% csrf_token %}

                <div class="input-group">
                  <input type="text" class="form-control" name="username" placeholder="Username">
                     <span class="input-group-text">
                          <svg class="bi bi-person-bounding-box" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                          <path fill-rule="evenodd" d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1h-3zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5zM.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5zm15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5z"/>
                          <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>

                     </span>


                </div>
                <br>
                <div class="input-group has-feedback has-search">
                    <span class="input-group-text">
                       <i class="material-icons md-48">vpn_key</i></span>


                    <input type="text" class="form-control" name="password" placeholder="Password">

                </div>
                <br>
                <div class="form-group">
                  <button type="button" class="btn btn-lg btn-primary">Log in <i class="material-icons md-48">done_all</i></button>
                </div>
                <div class="form-group forget-password">
                    <div class="row">
                        <div class="col">
                             <a href="#">Forget Password?</a>
                        </div>
                            <div class="col">
                             <a href="#">Done have account, Signup here!</a>
                            </div>
                        </div>
                    </div>

            </form>
            </div>
        </div>
      </div>
    </div>
    </div>
    <footer class="py-5 bg-black">
        <div class="container">
            <p class="text-center text-white m-0 small">@food_poverty</p>
        </div>
    </footer>
    </body>
</html>

sneaky/templates/landing.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<style>
    body { font-family: 'Circular Std Book'; font-style: normal; font-weight: normal; font-size: 16px; line-height: 27px; color: #808294; -webkit-font-smoothing: antialiased; background: #f8f8fb; }
.body-bg { background-color: #fbfbfc; }
h1, h2, h3, h4, h5, h6 { color: #181825; margin: 0px 0px 15px 0px; font-family: 'Circular Std Book'; }
h1 { font-size: 42px; line-height: 54px; letter-spacing: -1px; }
h2 { font-size: 34px; line-height: 44px; letter-spacing: -1px; }
h3 { font-size: 26px; line-height: 33px; letter-spacing: -1px; }
h4 { font-size: 20px; line-height: 31px; }
h5 { font-size: 16px; line-height: 21px; }
h6 { font-size: 13px; line-height: 21px; }
.h2 { font-size: 35px; line-height: 48px; letter-spacing: -1px; }
.h3, h3 {
    font-size: 26px;
    line-height: 38px;
}
p { margin: 0px 0px 24px 0px; }
p:last-child { margin: 0px; }
a { color: #3544ee; }
a:hover { color: #202db8; text-decoration: none; }
a:active, a:hover { outline: 0; text-decoration: none; }
a.text-primary:focus, a.text-primary:hover {
    color: #202db8!important;
}
.space-medium { padding-top: 100px; padding-bottom: 100px; }

.btn { font-size: 16px; padding: 11px 21px; border-radius: 4px; overflow: hidden; display: inline-block; vertical-align: middle; -webkit-transform: perspective(1px) translateZ(0); transform: perspective(1px) translateZ(0); box-shadow: 0 0 1px rgba(0, 0, 0, 0); overflow: hidden; -webkit-transition-duration: 0.3s; transition-duration: 0.3s; -webkit-transition-property: color, background-color; transition-property: color, background-color; transition: .3s ease; font-family: 'Circular Std Medium' !important; }
.btn-outline-primary { color: #3544ee; background-color: transparent; border-color: #3544ee; }
.btn-outline-primary:hover { color: #fff; background-color: #3544ee; border-color: #3544ee; }
.btn-outline-primary.focus, .btn-outline-primary:focus { color: #fff; background-color: #3544ee; border-color: #3544ee; box-shadow: 0 0 0 1px rgb(53, 68, 238); }
.btn-rounded { border-radius: 100px; }


.feature-block-v7 { }
.feature-block-v7.feature-block { margin-bottom: 30px; }
.feature-block-v7 .feature-content { }
.feature-block-v7 .feature-title { margin-bottom: 5px; font-size: 21px; }
.feature-block-v7 .feature-text { }
.feature-block-v7 .feature-icon { background-color: #e1e4fd; color: #3544ee; padding: 18px; font-size: 20px; display: block; text-align: center; width: 60px; height: 60px; margin-bottom: 30px; line-height: 1.5; border-radius: 100%; }
.feature-app-img { position: relative; text-align: center; }
.circle-1 { position: absolute; top: 50%; left: 50%; -webkit-transform: translate(-50%, -50%); transform: translate(-50%, -50%); width: 390px; height: 390px; background-color: #3be1a4; color: white; text-align: center; line-height: 100px; border-radius: 50%; font-size: 1.3rem; }
.circle-1:hover { cursor: pointer; }
.circle-1::after, .circle-1::before { content: ""; display: block; position: absolute; top: 0; left: 0; width: 390px; height: 390px; background: #3be1a4; border-radius: 50%; z-index: -1; -webkit-animation: grow 3s ease-in-out infinite; animation: grow 3s ease-in-out infinite; }
.circle-1::after { background: rgb(59, 225, 164); }
.circle-1::after::before { content: ""; display: block; position: absolute; top: 0; left: 0; width: 390px; height: 390px; background: #3be1a4; border-radius: 50%; z-index: -1; -webkit-animation: grow 3s ease-in-out infinite; animation: grow 3s ease-in-out infinite; }
.circle-1::before { background: rgb(59, 225, 164); -webkit-animation-delay: -0.5s; animation-delay: -0.5s; }
.circle-2 { position: absolute; top: 50%; left: 50%; -webkit-transform: translate(-50%, -50%); transform: translate(-50%, -50%); width: 390px; height: 390px; background-color: #9c4efb; color: white; text-align: center; line-height: 100px; border-radius: 50%; font-size: 1.3rem; }
.circle-2:hover { cursor: pointer; }
.circle-2::after, .circle-2::before { content: ""; display: block; position: absolute; top: 0; left: 0; width: 390px; height: 390px; background: #9c4efb; border-radius: 50%; z-index: -1; -webkit-animation: grow 3s ease-in-out infinite; animation: grow 3s ease-in-out infinite; }
.circle-2::after { background: rgba(156, 78, 251, .5); }
.circle-2::after::before { content: ""; display: block; position: absolute; top: 0; left: 0; width: 390px; height: 390px; background: #3be1a4; border-radius: 50%; z-index: -1; -webkit-animation: grow 3s ease-in-out infinite; animation: grow 3s ease-in-out infinite; }
.circle-2::before { background: rgba(156, 78, 251, .5); -webkit-animation-delay: -0.5s; animation-delay: -0.5s; }
.circle-3 { position: absolute; top: 50%; left: 50%; -webkit-transform: translate(-50%, -50%); transform: translate(-50%, -50%); width: 390px; height: 390px; background-color: #fb8645; color: white; text-align: center; line-height: 100px; border-radius: 50%; font-size: 1.3rem; }
.circle-3:hover { cursor: pointer; }
.circle-3::after, .circle-3::before { content: ""; display: block; position: absolute; top: 0; left: 0; width: 390px; height: 390px; background: #fb8645; border-radius: 50%; z-index: -1; -webkit-animation: grow 3s ease-in-out infinite; animation: grow 3s ease-in-out infinite; }
.circle-3::after { background: rgba(251, 134, 69, .5); }
.circle-3::after::before { content: ""; display: block; position: absolute; top: 0; left: 0; width: 390px; height: 390px; background: #3be1a4; border-radius: 50%; z-index: -1; -webkit-animation: grow 3s ease-in-out infinite; animation: grow 3s ease-in-out infinite; }
.circle-3::before { background: rgba(251, 134, 69, .5); -webkit-animation-delay: -0.5s; animation-delay: -0.5s; }
@-webkit-keyframes grow {
	0% { -webkit-transform: scale(1, 1); transform: scale(1, 1); opacity: 1; }
	100% { -webkit-transform: scale(1.8, 1.8); transform: scale(1.8, 1.8); opacity: 0; }
}
@keyframes grow {
	0% { -webkit-transform: scale(1, 1); transform: scale(1, 1); opacity: 1; }
	100% { -webkit-transform: scale(1.8, 1.8); transform: scale(1.8, 1.8); opacity: 0; }
}

</style>
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
 <div class="space-medium">
        <div class="container">
            <h1 class="text-center"> Chat Room</h1>
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-12 col-sm-12 col-12">
                    <div class="feature-block-v7 feature-block">
                        <div class="feature-icon text-brand bg-brand-light mb-5">
                            <i class="fas fa-paint-roller"></i>
                        </div>
                        <div class="feature-content">

                            <h2>Welcome to my chat application</h2>
                            <p class="lead">This application users can chat with group members!</p>
                            <hr class="m-t-30 m-b-30">
                             <a href="{% url 'login_user' %}" class="btn btn-rounded btn-outline-primary">Login</a>
                            <a href="{% url 'register_user' %}" class="btn btn-rounded btn-outline-primary">Signup</a>
                        </div>
                    </div>
                </div>
                <div class="offset-xl-1 col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
                    <div class="circle-1"></div>
                    <div class="feature-app-img">
                        <img src="https://jituchauhan.com/quanto/quanto/images/iphone-img-2.png" alt="App Landing Page Template - Quanto">
                    </div>
                </div>
            </div>
             <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center mt-4">
              Created for <a href="https://jituchauhan.com/quanto/" target="_blank" class="text-primary">ManojDjs</a>
              </div></div>
        </div>
    </div>

sneaky/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}
<h1 class="text-center">LOGIN</h1>

<div class="col-md-6 offset-md-3">
     <div class="shadow-sm p-3 mb-5 bg-white rounded">
    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="exampleInputEmail1">User Name:</label>
        <input type="text" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
<!--        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password:</label>
        <input type="password" class="form-control form-control-sm" id="exampleInputPassword1" name="password">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <br>
    <a href="{% url 'register_user' %}">Doesn't have account signup here! <span class="sr-only">(current)</span></a>
    </div>
 </div>

{% endblock %}

sneaky/templates/posts.html
{% extends "base.html" %}
{% block content %}

 {% if user.is_authenticated %}
    {% for post in posts %}
<div class="col-md-6 offset-md-3">
     <div class="shadow-sm p-3 mb-5 bg-white rounded">
                    <article class="media content-section">
                        <div class="row">
                        <div class="col">
                        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" height="70px" width="70px">
                        <br>
                        </div>
                        <div class="col">
                      <div class="media-body">
                        <div class="article-metadata">
                        <h3> <a class="mr-2" href="#">{{ post.author }}</a></h3>
                          <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                        </div>
                        <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
                        <p class="article-content">{{ post.content }}</p>
                      </div>
                        </div>
                            </div>
                    </article>
                     </div>
                </div>
                {% endfor %}
    {% else %}
<div class="col-md-6 offset-md-3">
    <div class="shadow p-3 mb-5 bg-white rounded">
    <div class="container">
    <h1><mark>Login/signup</mark> to view the posts</h1>
        </div>
    </div>
</div>
    {% endif %}


{% endblock %}

sneaky/templates/profile.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<div class="col-md-6 offset-md-3">

     <div class="shadow-sm p-3 mb-5 bg-white rounded">
         <h1 class="text-centre">Profile section</h1>
        <div class="content-section">
            <ul class="list-unstyled">
          <li class="media">
            <img  class="align-self-start mr-3" src="{{ user.profile.image.url }}">
            <div class="media-body">
                    <div class="media-body">
                    <label>User name:</label>
                <h6>{{ user.username }}</h6>
                    <label>Email address:</label>
                <h6>{{ user.email }}</h6>
                    <label>first name:</label>
                    <h6>{{ user.first_name }}</h6>
                    <label >Last name:</label>
                    <h6>{{ user.last_name }}</h6>
                    </div>
               </div>
          </li>
                <form method="Post" enctype="multipart/form-data">
                    {% csrf_token %}
                       {{ u_form|crispy }}
                        <br>
                        {{ p_form|crispy }}
<!--        {{ imgform }}-->

        <br>
        <div class="card-body">
    <input class="btn btn-primary stretched-link" type="submit" name="submit" value="Update">
            </div>
    </form>


            </ul>
        </div>
     </div>

</div>
{% endblock %}

sneaky/templates/signup.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="col-md-6 offset-md-3">
    <div class="content-section">
    <h1 class="text-centre">SIGNUP!</h1>
        <div class="shadow p-3 mb-5 bg-white rounded">
    <form method="Post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

        <br>
        <div class="card-body">
    <input class="btn btn-primary stretched-link" type="submit" name="submit" value="SignUP">
            </div>
    </form>
</div>
</div>
    </div>
{% endblock %}